const mongoose = require('mongoose');

/**
 * @fileoverview Message Model
 * Defines the schema for room-based chat messages.
 * Includes support for soft deletion, pinning, message editing with history,
 * threading/replies, and idempotency guarantees.
 */

const messageSchema = new mongoose.Schema({
  // ─── Core Message Data ──────────────────────────────────────────
  roomName: { type: String, required: true, index: true },

  // ─── Author Information ─────────────────────────────────────────
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  username: { type: String, required: true },
  role: { type: String, required: true },

  // ─── Message Content & State ────────────────────────────────────
  text: { type: String, required: true },

  deleted: { type: Boolean, default: false }, // Soft-delete flag
  pinned: { type: Boolean, default: false },
  editedAt: { type: Date, default: null },

  // ─── Threading / Replies ────────────────────────────────────────
  // If this message is a reply, parentMessageId points to the root message
  parentMessageId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Message',
    default: null,
    index: true,
  },
  // Cache of how many replies this message has received
  replyCount: {
    type: Number,
    default: 0,
  },

  // ─── Edit Tracking ──────────────────────────────────────────────
  // Audit log of all edits made to this message
  editHistory: [{
    originalText: { type: String, required: true },
    editedText: { type: String, required: true },
    editedAt: { type: Date, default: Date.now },
    editedBy: { // Tracks if a moderator edited someone else's message
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
  }],

  // ─── Idempotency ────────────────────────────────────────────────
  // Temporary ID generated by frontend. Used to prevent duplicate messages
  // if the client retries a request due to a network timeout.
  clientId: {
    type: String,
    sparse: true,
    unique: true
  },

}, { timestamps: true });

module.exports = mongoose.model('Message', messageSchema);